---
swagger: "2.0"
info:
  description: "ATTX GM internal API for orchestrating services and retrieving information from the Graph Store."
  version: "0.1"
  title: "ATTX GM API"
  contact:
    name: "ATTX project"
    url: "https://www.helsinki.fi/en/projects/attx-2016"
  license:
    name: "MIT"
basePath: "/"
tags:
- name: "GMservices"
  description: "Services handled by GM"
  externalDocs:
    description: "just use it"
    url: "https://attx-project.github.io/"
- name: "GMgraph"
  description: "Internal GM-API for graph store"
  externalDocs:
    description: "just use it"
    url: "https://attx-project.github.io/"
schemes:
- "http"
paths:
  /health:
    get:
      description: "Get health of GM-API."
      responses:
        200:
          description: "Successful response."
  /{apiversion}/service/index:
    post:
      tags:
      - "GMservices"
      operationId: "index_post"
      description: "Start ElasticSearch Indexing service."
      produces:
      - "application/json"
      parameters:
      - name: apiversion
        in: path
        required: true
        type: "integer"
      - in: "body"
        name: "indexing request"
        required: true
        schema:
          $ref: "#/definitions/Index"
      responses:
        202:
          description: "Accepted."
          schema:
            $ref: "#/definitions/IndexResult"
        400:
          description: "Invalid Input."
  /{apiversion}/service/prov:
    post:
      tags:
      - "GMservices"
      description: "Updates the Graph Store with provenance data."
      produces:
      - "application/json"
      parameters:
      - name: apiversion
        in: path
        required: true
        type: "integer"
      - in: "body"
        name: "prov request"
        required: true
        schema:
          $ref: "#/definitions/Prov"
      responses:
        202:
          description: "Accepted."
          schema:
            $ref: "#/definitions/ProvStatus"
        400:
          description: "Invalid Input."
  /{apiversion}/graph/query:
    post:
      tags:
      - "GMgraph"
      operationId: "graph_query"
      description: "Send a SPARQL query to the Graph Store"
      parameters:
      - name: apiversion
        in: path
        required: true
        type: "integer"
      - in: "body"
        name: "linking"
        required: true
        schema:
          $ref: "#/definitions/Query"
      responses:
        202:
          description: "Accepted."
        400:
          description: "Invalid Input."
  /{apiversion}/graph/update:
    post:
      tags:
      - "GMgraph"
      operationId: "graph_update"
      description: "Send an update query to the Graph Store."
      parameters:
      - name: apiversion
        in: path
        required: true
        type: "integer"
      - in: "body"
        name: "linking"
        required: true
        schema:
          $ref: "#/definitions/Query"
      responses:
        202:
          description: "Accepted."
        400:
          description: "Invalid Input."
  /{apiversion}/graph/list:
    get:
      tags:
      - "GMgraph"
      description: "Get list of Graphs."
      produces:
      - "application/json"
      parameters:
      - name: apiversion
        in: path
        required: true
        type: "integer"
      responses:
        200:
          description: "Successful response."
          schema:
            type: "array"
            items:
              type: "string"
        410:
          description: "No Graphs available."
  /{apiversion}/graph/statistics:
    get:
      tags:
      - "GMgraph"
      description: "Get status of the linking job."
      produces:
      - "application/json"
      parameters:
      - name: apiversion
        in: path
        required: true
        type: "integer"
      responses:
        200:
          description: "Successful response."
          schema:
            type: "object"
        410:
          description: "Statistics Unavailable."
  /{apiversion}/graph/{graphID}:
    get:
      tags:
      - "GMgraph"
      description: "Get status of the linking job."
      produces:
      - "application/json"
      parameters:
      - name: apiversion
        in: path
        required: true
        type: "integer"
      - name: "graphID"
        in: "path"
        description: "Fetch graph with a specific ID."
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Successful response."
          schema:
            type: "object"
        410:
          description: "Graph does not exist."
    delete:
      tags:
      - "GMgraph"
      description: "Delete graph with a certain ID."
      parameters:
      - name: "graphID"
        in: "path"
        description: "Fetch graph with a specific ID."
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "OK"
definitions:
  Index:
    allOf:
    - required:
      - "indexing"
      - "plugin"
      - "graphStore"
      - "targetEndpoint"
      properties:
        plugin:
          type: "string"
          description: "list of plugin names/IDs for different mappers"
          items:
            type: "string"
        targetEndpoint:
          type: "string"
        indexing:
          type: "object"
          properties: {}
        graphStore:
          type: "object"
          items:
            type: "string"
    - {}
  IndexResult:
    required:
    - "id"
    - "status"
    properties:
      id:
        type: "integer"
        format: "int64"
      status:
        type: "string"
  Prov:
    required:
    - "id"
    - "type"
    properties:
      id:
        type: "integer"
        format: "int64"
      type:
        type: "string"
      properties:
        type: "object"
        properties: {}
  ProvStatus:
    required:
    - "id"
    - "status"
    properties:
      id:
        type: "integer"
        format: "int64"
      status:
        type: "string"
  Query:
    required:
    - "graphStore"
    - "query"
    properties:
      graphStore:
        type: "object"
        properties: {}
      query:
        type: "object"
        properties: {}
