
#ATTX GM-API specification
swagger: '2.0'

info:
  version: "0.2"
  title: ATTX GM API
  description: ATTX GM internal  API for mapping the source data against a RML mapping configuration and communication between Graph Manager the Workflow Component and the Graph Store.
  contact:
    name: "ATTX project"
    url: http://helsinki.fi/library
  license:
    name: "MIT"

tags:
- name: "gmAPI"
  description: "Internal GM-API for graph manager"
  externalDocs:
    description: "just use it"
    url: http://helsinki.fi/library

schemes:
- "http"

basePath: /api/0.2/

paths:
  /map/{mapID}:
    get:
      tags:
        - "gmAPI"
      description: Get status of the mapping job.
      produces:
      - "text/turtle"
      - "application/ld+json"
      parameters:
        - in: path
          name: mapID
          description: ID of map that needs to be fetched
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: "Successful response."
        410:
          description: "Map Gone."
  /map:
    post:
      tags:
        - "gmAPI"
      parameters:
        - name: mapping
          in: body
          description: Mapping object to pass to the Graph Manager API.
          required: true
          schema:
            $ref: '#/definitions/Map'
      responses:
        202:
          description: "Accepted."
        405:
          description: "Invalid Input."
  /links:
    get:
     tags:
        - "gmAPI"
     description: Get the links in the Graph Store
     responses:
        200:
          description: "Successful response."
    post:
      tags:
        - "gmAPI"
      parameters:
        - name: linking
          in: body
          description: Linking input and output graphs.
          required: true
          schema:
            $ref: '#/definitions/Link'
      responses:
        202:
          description: "Accepted."
        405:
          description: "Invalid Input."
  /index:
    post:
      tags:
        - "gmAPI"
      parameters:
        - name: index
          in: body
          description: Triggering the index.
          required: true
          schema:
            $ref: '#/definitions/Index'
      responses:
        202:
          description: "Accepted."
        405:
          description: "Invalid Input."
definitions:
  Map:
    allOf:
      - required:
        - mapping
        - targetEndpoint
        - sourceGraphs
        properties:
          targetEndpoint:
            type: string
          mapping:
            type: object
          sourceGraphs:
            type: array
            items:
              type: string
  Index:
    allOf:
      - required:
        - targetEndpoint
        - index
        - type
        - id
        properties:
          targetEndpoint:
            type: string
          index:
            type: string
          type:
            type: string
          id:
            type: integer
          sourceGraphs:
            type: array
            items:
              type: string
  Link:
    allOf:
      - required:
        - inputGraph
        - outputGraph
        properties:
          inputGraph:
            type: string
          outputGraph:
            type: string
